### ISSUE TITLE
log to stderr not stdout

### ISSUE THREAD

**Issue by kapilt** [jmhale/okta-awscli#105]
I'm trying to source the default credential output, but i have some warnings in my output which cause problems. It looks like this is doing some manual log setup which is defaulting to stdout instead of stderr, switching to logging.basicConfig should resolve this.

**Comment by jmhale** [comment]
Hey @kapilt. I just submitted a review on your PR. Thanks for that!

Ultimately, I like the simplified logger set up, but I'd be more in favor of using a `--quiet`-type flag to support your use case, rather than moving the output behind either the `--verbose` or `--debug` flags.

Your use case is interesting, but I think that most still use this in a interactive way, so the changes in #106 would be confusing to some, since we'd be hiding some normal operational messages that direct the user how to proceed in a interactive scenario.
