### ISSUE TITLE
Duration

### ISSUE THREAD

**Issue by johnybradshaw** [jmhale/okta-awscli#43]
Is there anyway to adjust the STS token duration?

**Comment by jmhale** [comment]
We can add a `DurationSeconds` param to the `AssumeRoleWithSAML` call to STS here: https://github.com/jmhale/okta-awscli/blob/master/oktaawscli/aws_auth.py#L65-L67

We would need to add the appropriate mechanisms to allow this value to be read from the user's config file, if the value is present, else it falls back to the AWS default of `3600` seconds. 

The part where this gets hairy is if the AWS administrator sets a lower limit to the role session duration than what the user is trying to set in okta-awscli, which would cause the auth operation to fail.

We'd need to ensure that is handled gracefully, with a informative error message. Since we can't determine the role session limit programmatically (unless the user has `iam:GetRole` permissions), it would be entirely up to the user to know the correct value to set.

**Comment by ChrisLopezUK** [comment]
To be honest even with the problems you raise it would be worth while adding the parameter without further work.
One of the big problems we have are Terraform deployments hanging halfway once the authenticated session expires.
