### ISSUE TITLE
Encypted password

### ISSUE THREAD

**Issue by allieliongpailui** [jmhale/okta-awscli#52]
Can the okta password be encrypted in .okta-aws? How about skipping from storing the password? 
Thanks

**Comment by jmhale** [comment]
We can try to add a utility for the user to encrypt the password, then put the ciphertext in the config file, but I'm not sure if this is complexity that we want to support right now, since it means protecting the encryption key out of band.

You can omit the password from the config file and okta-awscli will prompt the user for it. 

In fact, in the example config in the README, we specifically call out that you shouldn't store the password in the config file unless you really know what you're doing (basically, add the password for rapid cycle debugging, then remove it).

I'm going to close this for now. If more people are really interested in adding an encrypted password feature, we can revisit.
